### Probando endpoints de usuarios
### Obtener todos los usuarios
GET http://localhost:3000/api/users

### Obtener un usuario por id
GET http://localhost:3000/api/users/1

### Crear un nuevo usuario con datos válido
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "email": "newuser@example.com",
  "password": "securepassword",
  "type": "user"
}

### Actualizar un usuario por su ID
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
  "email": "updateduser@example.com",
  "password": "newsecurepassword",
  "type": "admin"
}

### Eliminar un usuario por su ID me da error - COMPROBAR
DEL http://localhost:3000/api/users/5
Content-Type: application/json"


### Endpoints para profesores
### Ver estudiantes de un profesor. Em este caso el 1. 
GET http://localhost:3000/api/teachers/1/students
Content-Type: application/json

### Endpoints para activar usuarios

POST http://localhost:3000/api/users/1/active
Content-Type: application/json

### Obtener el estado de activación de un usuario.
GET http://localhost:3000/api/users/1/active
Content-Type: application/json

### No se puede borrar un usuario con profesor asociado
DELETE http://localhost:3000/api/users/3
Content-Type: application/json

### Borra profesor sin alumnos asociados
DELETE http://localhost:3000/api/teachers/3
Content-Type: application/json
